id: '17532665382690.3698011080372223'
kind: workflow
name: loadUniversityApplications
nameConfigured: true
steps:
  - id: '17532673366180.7424875092896536'
    type: customSQLQuery
    name: query
    params:
      - type: datasourceId
        value: NYUNGWA DIGITAL TECH_4N70PZBh8w
        valueType: custom
        mustSelectFirst: true
      - type: query
        value: ./query-query.sql
        valueType: interpolatedValue
        interpolationType: string
      - type: preparedQuery
        value: ./query-preparedQuery.sql
        valueType: interpolatedValue
      - type: preparedQueryParams
        value: []
        valueType: custom
      - type: customDatabaseName
        value: ''
        valueType: interpolatedValue
      - type: stepVersion
        value: 2
        valueType: custom
      - type: successMapper
        value: ''
        valueType: interpolatedValue
        interpolationType: code
      - type: failureMapper
        value: ''
        valueType: interpolatedValue
        interpolationType: code
      - type: mapperEnabled
        value: false
        valueType: custom
    level: 0
    fallthroughError: false
    isChanged: false
mode: manual
modeConfigured: true
parentPageId: '1'
config:
  shouldConfirm: false
  confirmMessage: >-
    Are you sure you'd like to proceed with
    "{{actions.loadUniversityApplications.name}}"?
  showSuccessToast: false
  successToast: Action "{{actions.loadUniversityApplications.name}}" successfully executed
  successToastDuration: '3000'
  successToastHideByClick: false
  showErrorToast: false
  errorToast: Action "{{actions.loadUniversityApplications.name}}" has failed
  errorToastDuration: '3000'
  errorToastHideByClick: false
  delay: '0'
  runWhenFirstReferenced: true
  preserveStateOnPageChange: false
